### PR TITLE
Use DateTime::createFromFormat to generate end date in DataController

### PR DESCRIPTION
**Pull request by Tropicao**
Linked to https://github.com/SimonMellerin/Pilea/issues/23
I do not observe the display issue on Welcome board when explicitely setting the format to build end date

### CODE REVIEW

**Comment by SimonMellerin** [comment]
Did this bugfix solved your problem ?

**Comment by SimonMellerin** [comment]
Can you give me the step to reproduce the error you try to fix with this PR ?

`new \DateTime('2019-10-01  23:59:59')` is a valid use of DateTime constructor, error must come from elsewhere I think

**Comment by SimonMellerin** [comment]
Alright, I get it, your error message is 
`[2019-10-02 23:05:29] request.CRITICAL: Uncaught PHP Exception Exception: "DateTime::__construct(): Failed to parse time string (2019-30-9 23:59:59) at position 6 (0): Unexpected character" at /var/www/pilea/src/Controller/DataController.php line 37 {"exception":"[object] (Exception(code: 0): DateTime::__construct(): Failed to parse time string (2019-30-9 23:59:59) at position 6 (0): Unexpected character at /var/www/pilea/src/Controller/DataController.php:37)"} []`

the given string is `2019-30-9 23:59:59` it should be `2019-30-09 23:59:59`

The real issue comes from `assets/js/homepage.js`
I shouldn't use `toLocaleDateString` function which may changes according to environments

**Comment by Tropicao** [comment]
Hi,
good to know you have managed to identify the issue. On my side, my fix seems to fix the issue, but after checking again, not sure if it does not introduce another issue, I have a weird summary board, even if this time it has values (I see september values in the October summary) : 
image

Since you have identified the real cause, I guess you can clause my submission.

**Pull request closed without merging**
